services:
  marmut:
    build:
      context: .
    env_file:
      - path: .env
        required: true
    networks:
      - marmut-network

networks:
  marmut-network:
    name: marmut-network
    external: true
