services:
  sonata:
    build:
      context: .
      dockerfile: Dockerfile.sonata
    restart: unless-stopped
    ports:
      - "2333:2333"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:2333/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - marmut-network

  marmut:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      sonata:
        condition: service_healthy
    env_file:
      - path: .env
        required: true
    environment:
      LAVALINK_NODE_NAME: Docker Sonata
      LAVALINK_NODE_URL: sonata:2333
      LAVALINK_NODE_AUTH: youshallnotpass
      LAVALINK_NODE_IS_SECURE: false
    networks:
      - marmut-network

networks:
  marmut-network:
    driver: bridge
