# syntax=docker/dockerfile:1

ARG NODELINK_VERSION=latest

FROM performanc/nodelink:${NODELINK_VERSION}

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY --chown=1000:1000 config.js ./config.js

EXPOSE 2333

USER 1000
