# syntax=docker/dockerfile:1

ARG NODELINK_VERSION=latest

FROM performanc/nodelink:${NODELINK_VERSION}

ENV NODE_ENV=production

WORKDIR /app

RUN mkdir -p /app/plugins /app/.cache && chown -R 1000:1000 /app/plugins /app/.cache

COPY --chown=1000:1000 config.js ./config.js

EXPOSE 2333

USER 1000
