export const enum ValidationErrorCode {
    CLIENT_NOT_IN_VOICE,
    MEMBER_NOT_IN_VOICE,
    MEMBER_NOT_IN_SAME_VOICE,
    QUEUE_MENU_NOT_FOR_USER,
    SEARCH_MENU_NOT_FOR_USER,
    NON_POSITIVE_SONG_POSITION,
    INVALID_VOICE_CHANNEL,
    MISSING_VOICE_CHANNEL,
    NON_JOINABLE_VOICE_CHANNEL,
}
